name: Jira Lint

on: [pull_request]

jobs:
  parse_commit_for_jira_id:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Lint
        uses: cleartax/jira-lint@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-base-url: https://smarsh.atlassian.net
          skip-branches: '^(main\/v\d+)$'
          pr-threshold: 1000
      - name: Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          parse-all-commits: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail if no Jira Key found in any commit message
        if: steps.jira_keys.outputs.jira-keys == ''
        shell: bash
        run: |
          echo "At least one commit message must include a Jira Key"
          echo "BUILD_STATE=failed" >> $GITHUB_ENV
          exit 1
      - name: Echo Jira Keys
        if: steps.jira_keys.outputs.jira-keys != ''
        shell: bash
        run: echo ${{steps.jira_keys.outputs.jira-keys}}
