---
name: Commit Message Check (rule in eval mode)

on: [pull_request]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check for JIRA Ticket in Each Commit
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: "[a-zA-Z][a-zA-Z0-9]{1,9}-[1-9][0-9]*"
          error: >2
            There should be at least one JIRA key in each commit.
            If you have commits without a key, you can fix this by
            rewriting your commit history using interactive rebase.
            https://www.atlassian.com/git/tutorials/rewriting-history
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          excludeTitle: "true" # optional: this excludes the title of a pull request
          checkAllCommitMessages: "true" # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token required if checkAllCommitMessages is true
      # - name: Check Commit Type
      #   uses: gsactions/commit-message-checker@v2
      #   with:
      #     pattern: '\[[^]]+\] .+$'
      #     flags: 'gm'
      #     error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      # - name: Check Line Length
      #   uses: gsactions/commit-message-checker@v2
      #   with:
      #     pattern: '^[^#].{74}'
      #     error: 'The maximum line length of 74 characters is exceeded.'
      #     excludeDescription: 'true' # optional: this excludes the description body of a pull request
      #     excludeTitle: 'true' # optional: this excludes the title of a pull request
      #     checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
      #     accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token required if checkAllCommitMessages is true
      # - name: Check for Resolves / Fixes
      #   uses: gsactions/commit-message-checker@v2
      #   with:
      #     pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
      #     error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'
