---
name: Git Secret Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.6.8
        with:
          path: ./
          extra_args: --only-verified
