name: Jira Status Check

on: [pull_request]

jobs:
  jira_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Test Jira Status Check
        uses: smarsh/jira-lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-base-url: https://smarsh.atlassian.net
          skip-branches: '^(main\/v\d+)$'
          pr-threshold: 1000
          skip-comments: true
          validate-issue-status: true
          allowed-issue-statuses: |
            Accepted
            To Do
            In Progress
            Work in progress
            Done
            Development
            Development Complete
            Technical Review
          fail-on-error: true
